Create contact form
ayebaishmo/portifolio_mobile_version pull request #3
Opened 2021-06-08 21:01 UTC by ayebaishmo

In this  branch we:
- Create contact from in HTML
- Design in CSS
- Update the README file 
- Fixed the lint errors

2021-06-08 22:02 UTC, Davidosky007 requested changes
Hi @ayebaishmo @sevinchek, 

Good job so far Team 👍 !
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
* Please check comments below and make the necessary changes 👍 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-06-08 23:42 UTC, ayebaishmo commented on index.html
> +                        <textarea class="txt-a" name="message" id="message" placeholder="Enter text here" maxlength="500" required>
The lint error dose not allow the type textarea

2021-06-08 23:58 UTC, Davidosky007 commented on index.html
> +                        <textarea class="txt-a" name="message" id="message" placeholder="Enter text here" maxlength="500" required>
ok 👍

2021-06-09 00:12 UTC, Davidosky007 commented on index.html
> +                        <textarea class="txt-a" name="message" id="message" placeholder="Enter text here" maxlength="500" required>
The form still submits when no message is entered [Link](https://www.loom.com/share/b5c80a8bec5448dbb27fa51d9814da9b)

2021-06-09 00:18 UTC, Davidosky007 requested changes
Hi @sevinchek @ayebaishmo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
* You are almost done 🙏 check the comments and make the necessary changes then submit for review
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-06-09 00:18 UTC, Davidosky007 commented on index.html
> +                        <textarea class="txt-a" name="message" id="message" placeholder="Enter text here" maxlength="500" required>
The form still submits when no message is entered check this video [Link](https://www.loom.com/share/b5c80a8bec5448dbb27fa51d9814da9b)

2021-06-09 09:56 UTC, ayebaishmo commented on index.html
> +                        <textarea class="txt-a" name="message" id="message" placeholder="Enter text here" maxlength="500" required>
> 
> 
> The form still submits when no message is entered check this video [Link](https://www.loom.com/share/b5c80a8bec5448dbb27fa51d9814da9b)
There is space with in the message that is why it submits, Back space and try submitting again. It won't submit

2021-06-09 09:57 UTC, merged