Create contact form
ayebaishmo/portifolio_mobile_version pull request #4
Opened 2021-06-09 11:46 UTC by ayebaishmo

In this branch the following was done:
Created a contact form with HTML
 Designed the contact form with CSS
Fixed all the lint errors

2021-06-09 12:24 UTC, DeliceLydia requested changes
## Hi @ayebaishmo ✋, 

Good job so far! However, there are some issues that you still need to work on to go to the next project but you are almost there!



## Required Changes ♻️
_Check the comments under the review._

### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-09 12:24 UTC, DeliceLydia commented on index.html
> +                        </textarea>
- [ ] Check why this form allows sending an empty text area when i removed that class 
`  <textarea
                      class=""
                      id="message"
                      name="message"
                      maxlength="500"
                      placeholder="Enter text here"
                      required
                    ></textarea>`
 it worked perfectly. please validate it!

2021-06-09 13:34 UTC, ayebaishmo commented on index.html
> +                        </textarea>
Hey It does not allow submission. Just press back space and remove the space.

2021-06-09 15:25 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi <STUDENT_MENTION>, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-09 15:31 UTC, merged

2021-06-10 14:15 UTC, Geoelycom reviewed
Good job but you should limit the use of divs and use more semantic tags

2021-06-10 14:20 UTC, eri8-9 reviewed
- Good job 💪🏼
- Keep working on your ability to choose a better syntax.

2021-06-10 14:28 UTC, eri8-9 reviewed
- I think you already did your changes so great job so far